SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    NOT NULL
    PRIMARY_KEY,
    utf8,
    EXTRA
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = 'alx_book_store'
    AND TABLE_NAME = 'Books';
